name: Java/Kotlin CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract version
        uses: amadornes/parse-properties-action@v1.0
        id: properties
        with:
          file: 'gradle.properties'

      - name: Create version
        id: version
        #language=bash
        run: |
          if [ "${{ github.head_ref || github.ref_name }}" == "main" ]; then
            # dont need to include -main at the end
            echo "version=${{ steps.properties.outputs.version }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          else
            echo "version=${{ steps.properties.outputs.version }}-${{ github.head_ref || github.ref_name }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.8'

      - name: Build with Gradle 8.8
        run: gradle -Pversion=${{steps.version.outputs.version}} build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: cutapi-${{ steps.version.outputs.version }}.jar
          path: ./build/libs/cutapi-*-all.jar
